In [2]:
import numpy as np
import pandas as pd

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.random.seed(42)
np.random.randint()

TypeError: randint() got an unexpected keyword argument 'start'

In [4]:
df = pd.read_csv("../3.1 UNZIP_ME_FOR_NOTEBOOKS_V4/DATA/tips.csv")

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    str    
 3   smoker            244 non-null    str    
 4   day               244 non-null    str    
 5   time              244 non-null    str    
 6   size              244 non-null    int64  
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    str    
 9   CC Number         244 non-null    int64  
 10  Payment ID        244 non-null    str    
dtypes: float64(3), int64(2), str(6)
memory usage: 21.1 KB


In [10]:
df[df['sex'] == 'Female'].value_counts().sum()

np.int64(87)

In [15]:
df[(df['sex'] == 'Male') & (df['smoker'] == "No")].value_counts().sum()

np.int64(97)

157

In [20]:
def last_four(cc_num:str):
    cc_num = str(cc_num)
    return cc_num[-4:]

In [21]:
df['CC Number'].apply(last_four)

0      3410
1      9230
2      1322
3      5994
4      7221
       ... 
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: str

In [37]:
def quality(total_bill,tip):
    if tip / total_bill < 0.25:
        return tip / total_bill
    else:
        return "other"

In [38]:
df[['total_bill','tip']].apply(lambda fd:quality(fd['total_bill'],fd['tip']),axis=1)

0      0.059447
1      0.160542
2      0.166587
3       0.13978
4      0.146808
         ...   
239    0.203927
240    0.073584
241    0.088222
242    0.098204
243    0.159744
Length: 244, dtype: object

In [25]:
np.vectorize()

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [39]:
df['CC Number']

0      False
1      False
2      False
3      False
4      False
       ...  
239    False
240    False
241    False
242    False
243    False
Name: CC Number, Length: 244, dtype: bool

In [49]:
mpg_df = pd.read_csv('../3.1 UNZIP_ME_FOR_NOTEBOOKS_V4/DATA/mpg.csv')

In [57]:
mpg_df.groupby('model_year').mean(numeric_only=True)['mpg']

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64