In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('../3.1 UNZIP_ME_FOR_NOTEBOOKS_V4/DATA/Advertising.csv')

In [5]:
X = df.drop('sales',axis=1)
y = df['sales']

In [7]:
from sklearn.preprocessing import PolynomialFeatures

In [8]:
poly_conv = PolynomialFeatures(degree=2)

In [9]:
poly_features = poly_conv.fit_transform(X)

poly_features

array([[1.00000e+00, 2.30100e+02, 3.78000e+01, ..., 1.42884e+03,
        2.61576e+03, 4.78864e+03],
       [1.00000e+00, 4.45000e+01, 3.93000e+01, ..., 1.54449e+03,
        1.77243e+03, 2.03401e+03],
       [1.00000e+00, 1.72000e+01, 4.59000e+01, ..., 2.10681e+03,
        3.18087e+03, 4.80249e+03],
       ...,
       [1.00000e+00, 1.77000e+02, 9.30000e+00, ..., 8.64900e+01,
        5.95200e+01, 4.09600e+01],
       [1.00000e+00, 2.83600e+02, 4.20000e+01, ..., 1.76400e+03,
        2.78040e+03, 4.38244e+03],
       [1.00000e+00, 2.32100e+02, 8.60000e+00, ..., 7.39600e+01,
        7.48200e+01, 7.56900e+01]], shape=(200, 10))

In [10]:
from sklearn.preprocessing import StandardScaler

In [11]:
scaler = StandardScaler()

In [12]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=42)

In [19]:
scaler.fit(X_train)

,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True


In [20]:
X_train_scaled = scaler.transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [21]:
from sklearn.linear_model import RidgeCV


In [22]:
ridge_cv = RidgeCV(alphas=(0.1,5,10))

In [23]:
ridge_cv.fit(X_train_scaled,y_train)

,"alphas alphas: array-like of shape (n_alphas,), default=(0.1, 1.0, 10.0)Array of alpha values to try.Regularization strength; must be a positive float. Regularizationimproves the conditioning of the problem and reduces the variance ofthe estimates. Larger values specify stronger regularization.Alpha corresponds to ``1 / (2C)`` in other linear models such as:class:`~sklearn.linear_model.LogisticRegression` or:class:`~sklearn.svm.LinearSVC`.If using Leave-One-Out cross-validation, alphas must be strictly positive.","(0.1, ...)"
,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto false, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"scoring scoring: str, callable, default=NoneThe scoring method to use for cross-validation. Options:- str: see :ref:`scoring_string_names` for options.- callable: a scorer callable object (e.g., function) with signature ``scorer(estimator, X, y)``. See :ref:`scoring_callable` for details.- `None`: negative :ref:`mean squared error ` if cv is None (i.e. when using leave-one-out cross-validation), or :ref:`coefficient of determination ` (:math:`R^2`) otherwise.",None
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the efficient Leave-One-Out cross-validation- integer, to specify the number of folds.- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if ``y`` is binary or multiclass,:class:`~sklearn.model_selection.StratifiedKFold` is used, else,:class:`~sklearn.model_selection.KFold` is used.Refer :ref:`User Guide ` for the variouscross-validation strategies that can be used here.",None
,"gcv_mode gcv_mode: {'auto', 'svd', 'eigen'}, default='auto'Flag indicating which strategy to use when performingLeave-One-Out Cross-Validation. Options are:: 'auto' : use 'svd' if n_samples > n_features, otherwise use 'eigen' 'svd' : force use of singular value decomposition of X when X is dense, eigenvalue decomposition of X^T.X when X is sparse. 'eigen' : force computation via eigendecomposition of X.X^TThe 'auto' mode is the default and is intended to pick the cheaperoption of the two depending on the shape of the training data.",None
,"store_cv_results store_cv_results: bool, default=FalseFlag indicating if the cross-validation values corresponding toeach alpha should be stored in the ``cv_results_`` attribute (seebelow). This flag is only compatible with ``cv=None`` (i.e. usingLeave-One-Out Cross-Validation)... versionchanged:: 1.5 Parameter name changed from `store_cv_values` to `store_cv_results`.",False
,"alpha_per_target alpha_per_target: bool, default=FalseFlag indicating whether to optimize the alpha value (picked from the`alphas` parameter list) for each target separately (for multi-outputsettings: multiple prediction targets). When set to `True`, afterfitting, the `alpha_` attribute will contain a value for each target.When set to `False`, a single alpha is used for all targets... versionadded:: 0.24",False


In [29]:
predictions = ridge_cv.predict(X_test_scaled)

predictions

array([17.20379564, 22.74576291, 20.39466028,  7.68339154, 24.39848339,
       12.62231119, 22.76362449,  8.1871436 , 12.13403065, 15.5792561 ,
        7.74066901,  8.1421529 , 11.93132277,  6.06817966, 10.49757796,
       12.28191927,  6.7834001 , 16.57875621, 10.57158033, 19.02386462,
       20.15078788, 13.84797101,  9.52893001, 22.10083104,  8.81686088,
        7.64132561, 22.35808309, 12.6102943 , 10.11498194,  6.09067061,
       11.65516178, 10.0777285 , 23.46364857,  9.8444954 , 15.38230434,
       21.06008648, 10.99409362, 20.18212487, 11.72693019,  6.4436853 ,
       10.69694097, 12.8094846 ,  9.21245947,  8.9207235 , 11.86416399,
        6.99267443,  9.9551003 , 14.67937626, 10.08759664, 11.2616187 ,
       14.04503519, 12.11986388,  8.97981222,  7.58871809,  8.38777959,
       10.84722568,  9.89867766, 25.27511723,  6.84376937, 11.93876269])

In [31]:
ridge_cv.coef_

array([ 0.        ,  4.49387328,  0.20933967,  0.22395242, -2.74022304,
        3.57254795, -0.49529753,  0.20766581,  0.15720171,  0.14494123])

In [25]:
from sklearn.metrics import mean_squared_error

In [27]:
mean_squared_error(y_test,predictions)

0.5125440116519137

In [28]:
from sklearn.linear_model import LassoCV

In [32]:
lasso_cv = LassoCV(alphas=(0.1,5,10))

In [33]:
lasso_cv.fit(X_train_scaled,y_train)

,"eps eps: float, default=1e-3Length of the path. ``eps=1e-3`` means that``alpha_min / alpha_max = 1e-3``.",0.001
,"n_alphas n_alphas: int, default=100Number of alphas along the regularization path... deprecated:: 1.7 `n_alphas` was deprecated in 1.7 and will be removed in 1.9. Use `alphas` instead.",'deprecated'
,"alphas alphas: array-like or int, default=NoneValues of alphas to test along the regularization path.If int, `alphas` values are generated automatically.If array-like, list of alpha values to use... versionchanged:: 1.7 `alphas` accepts an integer value which removes the need to pass `n_alphas`... deprecated:: 1.7 `alphas=None` was deprecated in 1.7 and will be removed in 1.9, at which point the default value will be set to 100.","(0.1, ...)"
,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto false, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"precompute precompute: 'auto', bool or array-like of shape (n_features, n_features), default='auto'Whether to use a precomputed Gram matrix to speed upcalculations. If set to ``'auto'`` let us decide. The Grammatrix can also be passed as argument.",'auto'
,"max_iter max_iter: int, default=1000The maximum number of iterations.",1000
,"tol tol: float, default=1e-4The tolerance for the optimization: if the updates are smaller or equal to``tol``, the optimization code checks the dual gap for optimality and continuesuntil it is smaller or equal to ``tol``.",0.0001
,"copy_X copy_X: bool, default=TrueIf ``True``, X will be copied; else, it may be overwritten.",True
,"cv cv: int, cross-validation generator or iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross-validation,- int, to specify the number of folds.- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For int/None inputs, :class:`~sklearn.model_selection.KFold` is used.Refer :ref:`User Guide ` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",None
,"verbose verbose: bool or int, default=FalseAmount of verbosity.",False
,"n_jobs n_jobs: int, default=NoneNumber of CPUs to use during the cross validation.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary `for more details.",None


In [34]:
lasso_predictions = lasso_cv.predict(X_test_scaled)

lasso_predictions

array([16.3986337 , 21.92921732, 21.95537549,  8.78244932, 23.86261108,
       12.21872401, 22.34338811,  8.79083469, 11.8641549 , 14.99262809,
        9.04825702,  8.4464278 , 12.14120113,  8.09539048,  9.82154322,
       11.66353588,  8.16726088, 16.11203832, 10.54649874, 19.00453898,
       20.05296975, 12.09948976, 10.46982228, 22.43364674,  9.12206376,
        8.05157726, 21.91199257, 12.03133227,  9.95631455,  8.12713624,
       11.17708545, 10.30993846, 22.60316645,  9.52632659, 16.60658191,
       20.96040328, 11.64096214, 21.24764851, 11.31584818,  7.49770173,
       10.20616549, 12.15981535,  9.76824562,  9.26391604, 11.63082136,
        7.86111279,  9.9062953 , 14.0706219 ,  9.62332065, 11.37679061,
       13.71640362, 11.45997166,  9.19110615,  8.65193923,  8.38255788,
       10.22472523, 10.09064907, 26.57581415,  8.30501436, 11.34503985])

In [ ]:
lasso_cv.coef_

array([ 0.        ,  1.52535747,  0.44499414,  0.        , -0.        ,
        3.51710834,  0.        ,  0.        ,  0.04588333,  0.        ])

In [37]:
mean_squared_error(y_test,lasso_predictions)

0.8328959253894369

In [38]:
from sklearn.linear_model import ElasticNetCV

In [39]:
elastic_cv = ElasticNetCV(n_alphas=5,l1_ratio=[0.2,0.5,0.8])

In [40]:
elastic_cv.fit(X_train_scaled,y_train)

c:\Users\kidus\Documents\vscode_python\machine_deep_learning\.venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1663: FutureWarning: 'n_alphas' was deprecated in 1.7 and will be removed in 1.9. 'alphas' now accepts an integer value which removes the need to pass 'n_alphas'. The default value of 'alphas' will change from None to 100 in 1.9. Pass an explicit value to 'alphas' and leave 'n_alphas' to its default value to silence this warning.
  warnings.warn(


,"l1_ratio l1_ratio: float or list of float, default=0.5Float between 0 and 1 passed to ElasticNet (scaling betweenl1 and l2 penalties). For ``l1_ratio = 0``the penalty is an L2 penalty. For ``l1_ratio = 1`` it is an L1 penalty.For ``0 < l1_ratio < 1``, the penalty is a combination of L1 and L2This parameter can be a list, in which case the differentvalues are tested by cross-validation and the one giving the bestprediction score is used. Note that a good choice of list ofvalues for l1_ratio is often to put more values close to 1(i.e. Lasso) and less close to 0 (i.e. Ridge), as in ``[.1, .5, .7,.9, .95, .99, 1]``.","[0.2, 0.5, ...]"
,"eps eps: float, default=1e-3Length of the path. ``eps=1e-3`` means that``alpha_min / alpha_max = 1e-3``.",0.001
,"n_alphas n_alphas: int, default=100Number of alphas along the regularization path, used for each l1_ratio... deprecated:: 1.7 `n_alphas` was deprecated in 1.7 and will be removed in 1.9. Use `alphas` instead.",5
,"alphas alphas: array-like or int, default=NoneValues of alphas to test along the regularization path, used for each l1_ratio.If int, `alphas` values are generated automatically.If array-like, list of alpha values to use... versionchanged:: 1.7 `alphas` accepts an integer value which removes the need to pass `n_alphas`... deprecated:: 1.7 `alphas=None` was deprecated in 1.7 and will be removed in 1.9, at which point the default value will be set to 100.",'warn'
,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto false, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"precompute precompute: 'auto', bool or array-like of shape (n_features, n_features), default='auto'Whether to use a precomputed Gram matrix to speed upcalculations. If set to ``'auto'`` let us decide. The Grammatrix can also be passed as argument.",'auto'
,"max_iter max_iter: int, default=1000The maximum number of iterations.",1000
,"tol tol: float, default=1e-4The tolerance for the optimization: if the updates are smaller or equal to``tol``, the optimization code checks the dual gap for optimality and continuesuntil it is smaller or equal to ``tol``.",0.0001
,"cv cv: int, cross-validation generator or iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross-validation,- int, to specify the number of folds.- :term:`CV splitter`,- An iterable yielding (train, test) splits as arrays of indices.For int/None inputs, :class:`~sklearn.model_selection.KFold` is used.Refer :ref:`User Guide ` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",None
,"copy_X copy_X: bool, default=TrueIf ``True``, X will be copied; else, it may be overwritten.",True
,"verbose verbose: bool or int, default=0Amount of verbosity.",0


In [42]:
elastic_predictions = elastic_cv.predict(X_test_scaled)

elastic_predictions

array([17.15358509, 22.69784286, 20.55034919,  7.7730346 , 24.27380578,
       12.58661314, 22.72657643,  8.24409406, 12.10959716, 15.55226023,
        7.87437613,  8.14895774, 11.88659249,  6.26976849, 10.4399969 ,
       12.23893565,  6.88918194, 16.54191571, 10.57945654, 19.00081817,
       20.15249266, 13.45209455,  9.63800102, 22.1497551 ,  8.84926452,
        7.66016653, 22.33130422, 12.5708598 , 10.10765694,  6.29058842,
       11.62162497, 10.11690291, 23.40976232,  9.67653272, 15.50921858,
       21.00246201, 11.07022609, 20.30388335, 11.70030635,  6.50936583,
       10.6617316 , 12.75206468,  9.26825286,  8.95898577, 11.84548946,
        7.05915655,  9.93964681, 14.64599835, 10.03795493, 11.29561763,
       14.0434772 , 12.06928405,  8.92433904,  7.6643737 ,  8.38047285,
       10.7946545 ,  9.93184939, 25.4041123 ,  6.98369951, 11.8800975 ])

In [43]:
mean_squared_error(y_test,elastic_predictions)

0.46669868472366877